export const cities = [
  { id: "Abottabad", name: "Abottabad" },
  { id: "Ahmadpur East", name: "Ahmadpur East" },
  { id: "Arifwala", name: "Arifwala" },
  { id: "Attock City", name: "Attock City" },
  { id: "Badin", name: "Badin" },
  { id: "Bahawalnagar", name: "Bahawalnagar" },
  { id: "Bahawalpur", name: "Bahawalpur" },
  { id: "Bannu", name: "Bannu" },
  { id: "Bhakkar", name: "Bhakkar" },
  { id: "Burewala", name: "Burewala" },
  { id: "Chakwal", name: "Chakwal" },
  { id: "Charsadda", name: "Charsadda" },
  { id: "Chichawatni", name: "Chichawatni" },
  { id: "Chaman", name: "Chaman" },
  { id: "Chishtian Mandi", name: "Chishtian Mandi" },
  { id: "Dadu", name: "Dadu" },
  { id: "Daska", name: "Daska" },
  { id: "Dera Ghazi Khan", name: "Dera Ghazi Khan" },
  { id: "Dera Ismail Khan", name: "Dera Ismail Khan" },
  { id: "Faisalabad", name: "Faisalabad" },
  { id: "Gujranwala", name: "Gujranwala" },
  { id: "Gujrat", name: "Gujrat" },
  { id: "Gwadar", name: "Gwadar" },
  { id: "Haripur", name: "Haripur" },
  { id: "Hasilpur", name: "Hasilpur" },
  { id: "Hafizabad", name: "Hafizabad" },
  { id: "Hangu", name: "Hangu" },
  { id: "Hyderabad", name: "Hyderabad" },
  { id: "Islamabad", name: "Islamabad" },
  { id: "Jacobabad", name: "Jacobabad" },
  { id: "Jaranwala", name: "Jaranwala" },
  { id: "Jhang", name: "Jhang" },
  { id: "Jhelum", name: "Jhelum" },
  { id: "Kamalia", name: "Kamalia" },
  { id: "Kamoke", name: "Kamoke" },
  { id: "Kandhkot", name: "Kandhkot" },
  { id: "Kasur", name: "Kasur" },
  { id: "Khairpur", name: "Khairpur" },
  { id: "Khanewal", name: "Khanewal" },
  { id: "Kharian", name: "Kharian" },
  { id: "Khuzdar", name: "Khuzdar" },
  { id: "Kohat", name: "Kohat" },
  { id: "Kot Addu", name: "Kot Addu" },
  { id: "Kotri", name: "Kotri" },
  { id: "Lahore", name: "Lahore" },
  { id: "Larkana", name: "Larkana" },
  { id: "Leiah", name: "Leiah" },
  { id: "Lodhran", name: "Lodhran" },
  { id: "Mandi Bahauddin", name: "Mandi Bahauddin" },
  { id: "Mardan", name: "Mardan" },
  { id: "Mianke Mor", name: "Mianke Mor" },
  { id: "Mianwali", name: "Mianwali" },
  { id: "Mirpur Khas", name: "Mirpur Khas" },
  { id: "Moro", name: "Moro" },
  { id: "Multan", name: "Multan" },
  { id: "Muridke", name: "Muridke" },
  { id: "Muzaffargarh", name: "Muzaffargarh" },
  { id: "Narowal", name: "Narowal" },
  { id: "Nawabshah", name: "Nawabshah" },
  { id: "Nowshera", name: "Nowshera" },
  { id: "Okara", name: "Okara" },
  { id: "Pakpattan", name: "Pakpattan" },
  { id: "Panjgur", name: "Panjgur" },
  { id: "Peshawar", name: "Peshawar" },
  { id: "Quetta", name: "Quetta" },
  { id: "Rahim Yar Khan", name: "Rahim Yar Khan" },
  { id: "Rajanpur", name: "Rajanpur" },
  { id: "Rawalpindi", name: "Rawalpindi" },
  { id: "Sadiqabad", name: "Sadiqabad" },
  { id: "Sahiwal", name: "Sahiwal" },
  { id: "Sanghar", name: "Sanghar" },
  { id: "Shahdadkot", name: "Shahdadkot" },
  { id: "Shahdadpur", name: "Shahdadpur" },
  { id: "Sheikhupura", name: "Sheikhupura" },
  { id: "Shikarpur", name: "Shikarpur" },
  { id: "Sialkot", name: "Sialkot" },
  { id: "Sukkur", name: "Sukkur" },
  { id: "Swabi", name: "Swabi" },
  { id: "Tando Adam", name: "Tando Adam" },
  { id: "Tando Allahyar", name: "Tando Allahyar" },
  { id: "Taunsa", name: "Taunsa" },
  { id: "Taxila", name: "Taxila" },
  { id: "Thatta", name: "Thatta" },
  { id: "Toba Tek Singh", name: "Toba Tek Singh" },
  { id: "Turbat", name: "Turbat" },
  { id: "Vehari", name: "Vehari" },
  { id: "Wah Cantonment", name: "Wah Cantonment" },
  { id: "Wazirabad", name: "Wazirabad" },
  { id: "Zhob", name: "Zhob" },
];
