export const cities = [
{ id : "Abbottabad", name : "Abbottabad"},
{ id : "Adilpur", name : "Adilpur"},
{ id : "Ahmadpur East", name : "Ahmadpur East"},
{ id : "Ahmadpur Sial", name : "Ahmadpur Sial"},
{ id : "Akora", name : "Akora"},
{ id : "Aliabad", name : "Aliabad"},
{ id : "Alik Ghund", name : "Alik Ghund"},
{ id : "Alipur", name : "Alipur"},
{ id : "Alizai", name : "Alizai"},
{ id : "Alpurai", name : "Alpurai"},
{ id : "Aman Garh", name : "Aman Garh"},
{ id : "Amirabad", name : "Amirabad"},
{ id : "Arifwala", name : "Arifwala"},
{ id : "Ashanagro Koto", name : "Ashanagro Koto"},
{ id : "Athmuqam", name : "Athmuqam"},
{ id : "Attock City", name : "Attock City"},
{ id : "Awaran", name : "Awaran"},
{ id : "Baddomalhi", name : "Baddomalhi"},
{ id : "Badin", name : "Badin"},
{ id : "Baffa", name : "Baffa"},
{ id : "Bagarji", name : "Bagarji"},
{ id : "Bagh", name : "Bagh"},
{ id : "Bahawalnagar", name : "Bahawalnagar"},
{ id : "Bahawalnagar", name : "Bahawalnagar"},
{ id : "Bahawalpur", name : "Bahawalpur"},
{ id : "Bakhri Ahmad Khan", name : "Bakhri Ahmad Khan"},
{ id : "Bandhi", name : "Bandhi"},
{ id : "Bannu", name : "Bannu"},
{ id : "Barishal", name : "Barishal"},
{ id : "Barkhan", name : "Barkhan"},
{ id : "Basirpur", name : "Basirpur"},
{ id : "Basti Dosa", name : "Basti Dosa"},
{ id : "Bat Khela", name : "Bat Khela"},
{ id : "Battagram", name : "Battagram"},
{ id : "Begowala", name : "Begowala"},
{ id : "Bela", name : "Bela"},
{ id : "Berani", name : "Berani"},
{ id : "Bhag", name : "Bhag"},
{ id : "Bhakkar", name : "Bhakkar"},
{ id : "Bhalwal", name : "Bhalwal"},
{ id : "Bhan", name : "Bhan"},
{ id : "Bhawana", name : "Bhawana"},
{ id : "Bhera", name : "Bhera"},
{ id : "Bhimbar", name : "Bhimbar"},
{ id : "Bhiria", name : "Bhiria"},
{ id : "Bhit Shah", name : "Bhit Shah"},
{ id : "Bhopalwala", name : "Bhopalwala"},
{ id : "Bozdar Wada", name : "Bozdar Wada"},
{ id : "Bulri", name : "Bulri"},
{ id : "Būrewāla", name : "Būrewāla"},
{ id : "Chak", name : "Chak"},
{ id : "Chak Azam Sahu", name : "Chak Azam Sahu"},
{ id : "Chak Five Hundred Seventy-five", name : "Chak Five Hundred Seventy-five"},
{ id : "Chak Jhumra", name : "Chak Jhumra"},
{ id : "Chak One Hundred Twenty Nine Left", name : "Chak One Hundred Twenty Nine Left"},
{ id : "Chak Thirty-one -Eleven Left", name : "Chak Thirty-one -Eleven Left"},
{ id : "Chak Two Hundred Forty-nine Thal Development Authority", name : "Chak Two Hundred Forty-nine Thal Development Authority"},   
{ id : "Chakwal", name : "Chakwal"},
{ id : "Chaman", name : "Chaman"},
{ id : "Chamber", name : "Chamber"},
{ id : "Charsadda", name : "Charsadda"},
{ id : "Chawinda", name : "Chawinda"},
{ id : "Chenab Nagar", name : "Chenab Nagar"},
{ id : "Cherat Cantonement", name : "Cherat Cantonement"},
{ id : "Chhor", name : "Chhor"},
{ id : "Chichawatni", name : "Chichawatni"},
{ id : "Chilas", name : "Chilas"},
{ id : "Chiniot", name : "Chiniot"},
{ id : "Chishtian", name : "Chishtian"},
{ id : "Chitral", name : "Chitral"},
{ id : "Choa Saidan Shah", name : "Choa Saidan Shah"},
{ id : "Chowki Jamali", name : "Chowki Jamali"},
{ id : "Chuchar-kana Mandi", name : "Chuchar-kana Mandi"},
{ id : "Chuhar Jamali", name : "Chuhar Jamali"},
{ id : "Chunian", name : "Chunian"},
{ id : "Dadhar", name : "Dadhar"},
{ id : "Dadu", name : "Dadu"},
{ id : "Daggar", name : "Daggar"},
{ id : "Daira Din Panah", name : "Daira Din Panah"},
{ id : "Dajal", name : "Dajal"},
{ id : "Dalbandin", name : "Dalbandin"},
{ id : "Dandot RS", name : "Dandot RS"},
{ id : "Daromehar", name : "Daromehar"},
{ id : "Darya Khan", name : "Darya Khan"},
{ id : "Darya Khan Marri", name : "Darya Khan Marri"},
{ id : "Daska Kalan", name : "Daska Kalan"},
{ id : "Dasu", name : "Dasu"},
{ id : "Daud Khel", name : "Daud Khel"},
{ id : "Daulatpur", name : "Daulatpur"},
{ id : "Daultala", name : "Daultala"},
{ id : "Daur", name : "Daur"},
{ id : "Dera Allahyar", name : "Dera Allahyar"},
{ id : "Dera Bugti", name : "Dera Bugti"},
{ id : "Dera Ghazi Khan", name : "Dera Ghazi Khan"},
{ id : "Dera Ismail Khan", name : "Dera Ismail Khan"},
{ id : "Dera Murad Jamali", name : "Dera Murad Jamali"},
{ id : "Dhanot", name : "Dhanot"},
{ id : "Dhaunkal", name : "Dhaunkal"},
{ id : "Dhoro Naro", name : "Dhoro Naro"},
{ id : "Digri", name : "Digri"},
{ id : "Dijkot", name : "Dijkot"},
{ id : "Dinan Bashnoian Wala", name : "Dinan Bashnoian Wala"},
{ id : "Dinga", name : "Dinga"},
{ id : "Dipalpur", name : "Dipalpur"},
{ id : "Diplo", name : "Diplo"},
{ id : "Doaba", name : "Doaba"},
{ id : "Dokri", name : "Dokri"},
{ id : "Duki", name : "Duki"},
{ id : "Dullewala", name : "Dullewala"},
{ id : "Dunga Bunga", name : "Dunga Bunga"},
{ id : "Dunyapur", name : "Dunyapur"},
{ id : "Eidgah", name : "Eidgah"},
{ id : "Eminabad", name : "Eminabad"},
{ id : "Faisalabad", name : "Faisalabad"},
{ id : "Faqirwali", name : "Faqirwali"},
{ id : "Faruka", name : "Faruka"},
{ id : "Fazilpur", name : "Fazilpur"},
{ id : "Fort Abbas", name : "Fort Abbas"},
{ id : "Gadani", name : "Gadani"},
{ id : "Gakuch", name : "Gakuch"},
{ id : "Gambat", name : "Gambat"},
{ id : "Gandava", name : "Gandava"},
{ id : "Garh Maharaja", name : "Garh Maharaja"},
{ id : "Garhi Khairo", name : "Garhi Khairo"},
{ id : "Garhiyasin", name : "Garhiyasin"},
{ id : "Gharo", name : "Gharo"},
{ id : "Ghauspur", name : "Ghauspur"},
{ id : "Ghotki", name : "Ghotki"},
{ id : "Gilgit", name : "Gilgit"},
{ id : "Gojra", name : "Gojra"},
{ id : "Goth Garelo", name : "Goth Garelo"},
{ id : "Goth Phulji", name : "Goth Phulji"},
{ id : "Goth Radhan", name : "Goth Radhan"},
{ id : "Gujar Khan", name : "Gujar Khan"},
{ id : "Gujranwala", name : "Gujranwala"},
{ id : "Gujrat", name : "Gujrat"},
{ id : "Gulishah Kach", name : "Gulishah Kach"},
{ id : "Gwadar", name : "Gwadar"},
{ id : "Hadali", name : "Hadali"},
{ id : "Hafizabad", name : "Hafizabad"},
{ id : "Hala", name : "Hala"},
{ id : "Hangu", name : "Hangu"},
{ id : "Haripur", name : "Haripur"},
{ id : "Harnai", name : "Harnai"},
{ id : "Harnoli", name : "Harnoli"},
{ id : "Harunabad", name : "Harunabad"},
{ id : "Hasilpur", name : "Hasilpur"},
{ id : "Hattian Bala", name : "Hattian Bala"},
{ id : "Haveli Lakha", name : "Haveli Lakha"},
{ id : "Havelian", name : "Havelian"},
{ id : "Hazro City", name : "Hazro City"},
{ id : "Hingorja", name : "Hingorja"},
{ id : "Hujra Shah Muqim", name : "Hujra Shah Muqim"},
{ id : "Hyderabad", name : "Hyderabad"},
{ id : "Islamabad", name : "Islamabad"},
{ id : "Islamkot", name : "Islamkot"},
{ id : "Jacobabad", name : "Jacobabad"},
{ id : "Jahanian Shah", name : "Jahanian Shah"},
{ id : "Jalalpur Jattan", name : "Jalalpur Jattan"},
{ id : "Jalalpur Pirwala", name : "Jalalpur Pirwala"},
{ id : "Jampur", name : "Jampur"},
{ id : "Jamshoro", name : "Jamshoro"},
{ id : "Jand", name : "Jand"},
{ id : "Jandiala Sher Khan", name : "Jandiala Sher Khan"},
{ id : "Jaranwala", name : "Jaranwala"},
{ id : "Jati", name : "Jati"},
{ id : "Jatoi Shimali", name : "Jatoi Shimali"},
{ id : "Jauharabad", name : "Jauharabad"},
{ id : "Jhang City", name : "Jhang City"},
{ id : "Jhang Sadr", name : "Jhang Sadr"},
{ id : "Jhawarian", name : "Jhawarian"},
{ id : "Jhelum", name : "Jhelum"},
{ id : "Jhol", name : "Jhol"},
{ id : "Jiwani", name : "Jiwani"},
{ id : "Johi", name : "Johi"},
{ id : "Jām Sāhib", name : "Jām Sāhib"},
{ id : "Kabirwala", name : "Kabirwala"},
{ id : "Kadhan", name : "Kadhan"},
{ id : "Kahna Nau", name : "Kahna Nau"},
{ id : "Kahror Pakka", name : "Kahror Pakka"},
{ id : "Kahuta", name : "Kahuta"},
{ id : "Kakad Wari Dir Upper", name : "Kakad Wari Dir Upper"},
{ id : "Kalabagh", name : "Kalabagh"},
{ id : "Kalaswala", name : "Kalaswala"},
{ id : "Kalat", name : "Kalat"},
{ id : "Kaleke Mandi", name : "Kaleke Mandi"},
{ id : "Kallar Kahar", name : "Kallar Kahar"},
{ id : "Kalur Kot", name : "Kalur Kot"},
{ id : "Kamalia", name : "Kamalia"},
{ id : "Kamar Mushani", name : "Kamar Mushani"},
{ id : "Kambar", name : "Kambar"},
{ id : "Kamoke", name : "Kamoke"},
{ id : "Kamra", name : "Kamra"},
{ id : "Kandhkot", name : "Kandhkot"},
{ id : "Kandiari", name : "Kandiari"},
{ id : "Kandiaro", name : "Kandiaro"},
{ id : "Kanganpur", name : "Kanganpur"},
{ id : "Karachi", name : "Karachi"},
{ id : "Karak", name : "Karak"},
{ id : "Karaundi", name : "Karaundi"},
{ id : "Kario Ghanwar", name : "Kario Ghanwar"},
{ id : "Karor", name : "Karor"},
{ id : "Kashmor", name : "Kashmor"},
{ id : "Kasur", name : "Kasur"},
{ id : "Keshupur", name : "Keshupur"},
{ id : "Keti Bandar", name : "Keti Bandar"},
{ id : "Khadan Khak", name : "Khadan Khak"},
{ id : "Khadro", name : "Khadro"},
{ id : "Khairpur", name : "Khairpur"},
{ id : "Khairpur Mir’s", name : "Khairpur Mir’s"},
{ id : "Khairpur Nathan Shah", name : "Khairpur Nathan Shah"},
{ id : "Khairpur Tamewah", name : "Khairpur Tamewah"},
{ id : "Khalabat", name : "Khalabat"},
{ id : "Khandowa", name : "Khandowa"},
{ id : "Khanewal", name : "Khanewal"},
{ id : "Khangah Dogran", name : "Khangah Dogran"},
{ id : "Khangarh", name : "Khangarh"},
{ id : "Khanpur", name : "Khanpur"},
{ id : "Khanpur Mahar", name : "Khanpur Mahar"},
{ id : "Kharan", name : "Kharan"},
{ id : "Kharian", name : "Kharian"},
{ id : "Khewra", name : "Khewra"},
{ id : "Khurrianwala", name : "Khurrianwala"},
{ id : "Khushāb", name : "Khushāb"},
{ id : "Khuzdar", name : "Khuzdar"},
{ id : "Kohat", name : "Kohat"},
{ id : "Kohlu", name : "Kohlu"},
{ id : "Kot Addu", name : "Kot Addu"},
{ id : "Kot Diji", name : "Kot Diji"},
{ id : "Kot Ghulam Muhammad", name : "Kot Ghulam Muhammad"},
{ id : "Kot Malik Barkhurdar", name : "Kot Malik Barkhurdar"},
{ id : "Kot Mumin", name : "Kot Mumin"},
{ id : "Kot Radha Kishan", name : "Kot Radha Kishan"},
{ id : "Kot Rajkour", name : "Kot Rajkour"},
{ id : "Kot Samaba", name : "Kot Samaba"},
{ id : "Kot Sultan", name : "Kot Sultan"},
{ id : "Kotli", name : "Kotli"},
{ id : "Kotli Loharan", name : "Kotli Loharan"},
{ id : "Kotri", name : "Kotri"},
{ id : "Kulachi", name : "Kulachi"},
{ id : "Kundian", name : "Kundian"},
{ id : "Kunjah", name : "Kunjah"},
{ id : "Kunri", name : "Kunri"},
{ id : "Lachi", name : "Lachi"},
{ id : "Ladhewala Waraich", name : "Ladhewala Waraich"},
{ id : "Lahore", name : "Lahore"},
{ id : "Lakhi", name : "Lakhi"},
{ id : "Lakki", name : "Lakki"},
{ id : "Lala Musa", name : "Lala Musa"},
{ id : "Lalian", name : "Lalian"},
{ id : "Landi Kotal", name : "Landi Kotal"},
{ id : "Larkana", name : "Larkana"},
{ id : "Layyah", name : "Layyah"},
{ id : "Liliani", name : "Liliani"},
{ id : "Lodhran", name : "Lodhran"},
{ id : "Loralai", name : "Loralai"},
{ id : "Mach", name : "Mach"},
{ id : "Madeji", name : "Madeji"},
{ id : "Mailsi", name : "Mailsi"},
{ id : "Malakand", name : "Malakand"},
{ id : "Malakwal", name : "Malakwal"},
{ id : "Malakwal City", name : "Malakwal City"},
{ id : "Malir Cantonment", name : "Malir Cantonment"},
{ id : "Mamu Kanjan", name : "Mamu Kanjan"},
{ id : "Mananwala", name : "Mananwala"},
{ id : "Mandi Bahauddin", name : "Mandi Bahauddin"},
{ id : "Mangla", name : "Mangla"},
{ id : "Mankera", name : "Mankera"},
{ id : "Mansehra", name : "Mansehra"},
{ id : "Mardan", name : "Mardan"},
{ id : "Mastung", name : "Mastung"},
{ id : "Matiari", name : "Matiari"},
{ id : "Matli", name : "Matli"},
{ id : "Mehar", name : "Mehar"},
{ id : "Mehmand Chak", name : "Mehmand Chak"},
{ id : "Mehrabpur", name : "Mehrabpur"},
{ id : "Mian Channun", name : "Mian Channun"},
{ id : "Mianke Mor", name : "Mianke Mor"},
{ id : "Mianwali", name : "Mianwali"},
{ id : "Minchianabad", name : "Minchianabad"},
{ id : "Mingora", name : "Mingora"},
{ id : "Miran Shah", name : "Miran Shah"},
{ id : "Miro Khan", name : "Miro Khan"},
{ id : "Mirpur Bhtoro", name : "Mirpur Bhtoro"},
{ id : "Mirpur Khas", name : "Mirpur Khas"},
{ id : "Mirpur Mathelo", name : "Mirpur Mathelo"},
{ id : "Mirpur Sakro", name : "Mirpur Sakro"},
{ id : "Mirwah Gorchani", name : "Mirwah Gorchani"},
{ id : "Mitha Tiwana", name : "Mitha Tiwana"},
{ id : "Mithi", name : "Mithi"},
{ id : "Moro", name : "Moro"},
{ id : "Moza Shahwala", name : "Moza Shahwala"},
{ id : "Multan", name : "Multan"},
{ id : "Muridke", name : "Muridke"},
{ id : "Murree", name : "Murree"},
{ id : "Musa Khel Bazar", name : "Musa Khel Bazar"},
{ id : "Mustafābād", name : "Mustafābād"},
{ id : "Muzaffargarh", name : "Muzaffargarh"},
{ id : "Muzaffarābād", name : "Muzaffarābād"},
{ id : "Nabisar", name : "Nabisar"},
{ id : "Nankana Sahib", name : "Nankana Sahib"},
{ id : "Narang Mandi", name : "Narang Mandi"},
{ id : "Narowal", name : "Narowal"},
{ id : "Nasirabad", name : "Nasirabad"},
{ id : "Naudero", name : "Naudero"},
{ id : "Naukot", name : "Naukot"},
{ id : "Naushahra Virkan", name : "Naushahra Virkan"},
{ id : "Naushahro Firoz", name : "Naushahro Firoz"},
{ id : "Nawabshah", name : "Nawabshah"},
{ id : "Nazir Town", name : "Nazir Town"},
{ id : "New Bādāh", name : "New Bādāh"},
{ id : "New Mirpur", name : "New Mirpur"},
{ id : "Noorabad", name : "Noorabad"},
{ id : "Nowshera", name : "Nowshera"},
{ id : "Nowshera Cantonment", name : "Nowshera Cantonment"},
{ id : "Nushki", name : "Nushki"},
{ id : "Okara", name : "Okara"},
{ id : "Ormara", name : "Ormara"},
{ id : "Pabbi", name : "Pabbi"},
{ id : "Pad Idan", name : "Pad Idan"},
{ id : "Paharpur", name : "Paharpur"},
{ id : "Pakpattan", name : "Pakpattan"},
{ id : "Panjgur", name : "Panjgur"},
{ id : "Pano Aqil", name : "Pano Aqil"},
{ id : "Parachinar", name : "Parachinar"},
{ id : "Pasni", name : "Pasni"},
{ id : "Pasrur", name : "Pasrur"},
{ id : "Pattoki", name : "Pattoki"},
{ id : "Peshawar", name : "Peshawar"},
{ id : "Phalia", name : "Phalia"},
{ id : "Pind Dadan Khan", name : "Pind Dadan Khan"},
{ id : "Pindi Bhattian", name : "Pindi Bhattian"},
{ id : "Pindi Gheb", name : "Pindi Gheb"},
{ id : "Pir Jo Goth", name : "Pir Jo Goth"},
{ id : "Pir Mahal", name : "Pir Mahal"},
{ id : "Pishin", name : "Pishin"},
{ id : "Pithoro", name : "Pithoro"},
{ id : "Qadirpur Ran", name : "Qadirpur Ran"},
{ id : "Qila Abdullah", name : "Qila Abdullah"},
{ id : "Qila Saifullah", name : "Qila Saifullah"},
{ id : "Quetta", name : "Quetta"},
{ id : "Rahim Yar Khan", name : "Rahim Yar Khan"},
{ id : "Raiwind", name : "Raiwind"},
{ id : "Raja Jang", name : "Raja Jang"},
{ id : "Rajanpur", name : "Rajanpur"},
{ id : "Rajo Khanani", name : "Rajo Khanani"},
{ id : "Ranipur", name : "Ranipur"},
{ id : "Rasulnagar", name : "Rasulnagar"},
{ id : "Ratodero", name : "Ratodero"},
{ id : "Rawala Kot", name : "Rawala Kot"},
{ id : "Rawalpindi", name : "Rawalpindi"},
{ id : "Renala Khurd", name : "Renala Khurd"},
{ id : "Risalpur Cantonment", name : "Risalpur Cantonment"},
{ id : "Rohri", name : "Rohri"},
{ id : "Rojhan", name : "Rojhan"},
{ id : "Rustam", name : "Rustam"},
{ id : "Saddiqabad", name : "Saddiqabad"},
{ id : "Sahiwal", name : "Sahiwal"},
{ id : "Sahiwal", name : "Sahiwal"},
{ id : "Saidu Sharif", name : "Saidu Sharif"},
{ id : "Sakrand", name : "Sakrand"},
{ id : "Samaro", name : "Samaro"},
{ id : "Sambrial", name : "Sambrial"},
{ id : "Sanghar", name : "Sanghar"},
{ id : "Sangla Hill", name : "Sangla Hill"},
{ id : "Sanjwal", name : "Sanjwal"},
{ id : "Sann", name : "Sann"},
{ id : "Sarai Alamgir", name : "Sarai Alamgir"},
{ id : "Sarai Naurang", name : "Sarai Naurang"},
{ id : "Sarai Sidhu", name : "Sarai Sidhu"},
{ id : "Sargodha", name : "Sargodha"},
{ id : "Sehwan", name : "Sehwan"},
{ id : "Setharja Old", name : "Setharja Old"},
{ id : "Shabqadar", name : "Shabqadar"},
{ id : "Shahdad Kot", name : "Shahdad Kot"},
{ id : "Shahdadpur", name : "Shahdadpur"},
{ id : "Shahkot", name : "Shahkot"},
{ id : "Shahpur", name : "Shahpur"},
{ id : "Shahpur Chakar", name : "Shahpur Chakar"},
{ id : "Shahr Sultan", name : "Shahr Sultan"},
{ id : "Shakargarh", name : "Shakargarh"},
{ id : "Sharqpur Sharif", name : "Sharqpur Sharif"},
{ id : "Shekhupura", name : "Shekhupura"},
{ id : "Shikarpur", name : "Shikarpur"},
{ id : "Shingli Bala", name : "Shingli Bala"},
{ id : "Shinpokh", name : "Shinpokh"},
{ id : "Shorkot", name : "Shorkot"},
{ id : "Shujaabad", name : "Shujaabad"},
{ id : "Sialkot", name : "Sialkot"},
{ id : "Sibi", name : "Sibi"},
{ id : "Sillanwali", name : "Sillanwali"},
{ id : "Sinjhoro", name : "Sinjhoro"},
{ id : "Skardu", name : "Skardu"},
{ id : "Sobhodero", name : "Sobhodero"},
{ id : "Sodhri", name : "Sodhri"},
{ id : "Sohbatpur", name : "Sohbatpur"},
{ id : "Sukheke Mandi", name : "Sukheke Mandi"},
{ id : "Sukkur", name : "Sukkur"},
{ id : "Surab", name : "Surab"},
{ id : "Surkhpur", name : "Surkhpur"},
{ id : "Swabi", name : "Swabi"},
{ id : "Sīta Road", name : "Sīta Road"},
{ id : "Talagang", name : "Talagang"},
{ id : "Talamba", name : "Talamba"},
{ id : "Talhar", name : "Talhar"},
{ id : "Tandlianwala", name : "Tandlianwala"},
{ id : "Tando Adam", name : "Tando Adam"},
{ id : "Tando Allahyar", name : "Tando Allahyar"},
{ id : "Tando Bago", name : "Tando Bago"},
{ id : "Tando Jam", name : "Tando Jam"},
{ id : "Tando Mitha Khan", name : "Tando Mitha Khan"},
{ id : "Tando Muhammad Khan", name : "Tando Muhammad Khan"},
{ id : "Tangi", name : "Tangi"},
{ id : "Tangwani", name : "Tangwani"},
{ id : "Tank", name : "Tank"},
{ id : "Taunsa", name : "Taunsa"},
{ id : "Thal", name : "Thal"},
{ id : "Tharu Shah", name : "Tharu Shah"},
{ id : "Thatta", name : "Thatta"},
{ id : "Thul", name : "Thul"},
{ id : "Timargara", name : "Timargara"},
{ id : "Toba Tek Singh", name : "Toba Tek Singh"},
{ id : "Topi", name : "Topi"},
{ id : "Turbat", name : "Turbat"},
{ id : "Ubauro", name : "Ubauro"},
{ id : "Umarkot", name : "Umarkot"},
{ id : "Upper Dir", name : "Upper Dir"},
{ id : "Usta Muhammad", name : "Usta Muhammad"},
{ id : "Uthal", name : "Uthal"},
{ id : "Utmanzai", name : "Utmanzai"},
{ id : "Vihari", name : "Vihari"},
{ id : "Wana", name : "Wana"},
{ id : "Warah", name : "Warah"},
{ id : "Wazirabad", name : "Wazirabad"},
{ id : "Yazman", name : "Yazman"},
{ id : "Zafarwal", name : "Zafarwal"},
{ id : "Zahir Pir", name : "Zahir Pir"},
{ id : "Zaida", name : "Zaida"},
{ id : "Zhob", name : "Zhob"},
{ id : "Ziarat", name : "Ziarat"},
];
