export const departments = [
  { id: "Registrar's Office", name: "Registrar's Office" },
  { id: "AAO, Pension & Billing", name: "AAO, Pension & Billing" },
  { id: "Treasure Department", name: "Treasure Department" },
  {
    id: "Directorate Of Purchase & Store",
    name: "Directorate Of Purchase & Store",
  },
  { id: "Department Of Examination", name: "Department Of Examination" },
  { id: "Department Of Admission", name: "Department Of Admission" },
  { id: "Transport Office", name: "Transport Office" },
  { id: "Secrecy Section", name: "Secrecy Section" },
  { id: "Conduct Section", name: "Conduct Section" },
  { id: "Medical Center", name: "Medical Center" },
  { id: "Directorate of Works", name: "Directorate of Works" },
  { id: "Public Relation Office", name: "Public Relation Office" },
  { id: "Security Office", name: "Security Office" },
  { id: "Department of Chemistry", name: "Department of Chemistry" },
  { id: "Department of Physics", name: "Department of Physics" },
  { id: "Department of Biology", name: "Department of Biology" },
  { id: "Environment Sciences", name: "Environment Sciences" },
  { id: "Department of Statistic", name: "Department of Statistic" },
  { id: "Directorate of BASR", name: "Directorate of BASR" },
  { id: "Directorate of ICT", name: "Directorate of ICT" },
  { id: "Secondary T Education", name: "Secondary T Education" },
  { id: "DNFCE Department", name: "DNFCE Department" },
  { id: "ECE & ETE Department", name: "ECE & ETE Department" },
  { id: "EPPS & L Department", name: "EPPS & L Department" },
  {
    id: "Department of Special Education",
    name: "Department of Special Education",
  },
  { id: "Science Education", name: "Science Education" },
  { id: "Directorate of (IC&E)", name: "Directorate of (IC&E)" },
  { id: "Hostels", name: "Hostels" },
  { id: "Research & ORIC", name: "Research & ORIC" },
  { id: "VC Office", name: "VC Office" },
  { id: "IET", name: "IET" },
  { id: "Directorate of QEC", name: "Directorate of QEC" },
  { id: "Mass Com", name: "Mass Com" },
  { id: "Central Library", name: "Central Library" },
  { id: "Pakistani Languages", name: "Pakistani Languages" },
  { id: "Shariah Law", name: "Shariah Law" },
  {
    id: "Home & Health Nutritional Sciences",
    name: "Home & Health Nutritional Sciences",
  },
  { id: "Agriculture Sciences", name: "Agriculture Sciences" },
  { id: "Library Information Sciences", name: "Library Information Sciences" },
  { id: "Mathematics", name: "Mathematics" },
  { id: "Iqbaliat", name: "Iqbaliat" },
  { id: "Urdu", name: "Urdu" },
  { id: "English", name: "English" },
  { id: "Economics", name: "Economics" },
  { id: "Pakistan Studies", name: "Pakistan Studies" },
  { id: "History", name: "History" },
  { id: "Computer Sciences", name: "Computer Sciences" },
  { id: "Arabic", name: "Arabic" },
  { id: "Hedit & Science", name: "Hedit & Science" },
  { id: "Interfaith Studies", name: "Interfaith Studies" },
  { id: "AP & CP", name: "AP & CP" },
  { id: "Sociology", name: "Sociology" },
  { id: "Women Studies", name: "Women Studies" },
  { id: "Editing Cell", name: "Editing Cell" },
  { id: "Quran & Tafseer", name: "Quran & Tafseer" },
  {
    id: "Islamic Thought Culture & History",
    name: "Islamic Thought Culture & History",
  },
  { id: "Seerah Studies", name: "Seerah Studies" },
  { id: "Business Administration", name: "Business Administration" },
  { id: "Commerce", name: "Commerce" },
  { id: "Director Regional Services", name: "Director Regional Services" },
  {
    id: "Directorate of Students Affairs",
    name: "Directorate of Students Affairs",
  },
  { id: "Mailing Section", name: "Mailing Section" },
  { id: "Print Production Unit", name: "Print Production Unit" },
  { id: "Regional Campus Islamabad", name: "Regional Campus Islamabad" },
  { id: "Regional Campus Rawalpindi", name: "Regional Campus Rawalpindi" },
  { id: "Regional Campus Quetta", name: "Regional Campus Quetta" },
  { id: "Regional Campus Lahore", name: "Regional Campus Lahore" },
  { id: "Regional Campus Peshawar", name: "Regional Campus Peshawar" },
  { id: "Regional Campus Karachi", name: "Regional Campus Karachi" },
  { id: "Regional Center Malir", name: "Regional Center Malir" },
  { id: "Regional Campus Muzaffarabad", name: "Regional Campus Muzaffarabad" },
];
